### ISSUE TITLE
Feature request:  Display of Units

### ISSUE THREAD

**Issue by xX-Nexus-Xx** [hotNipi/node-red-dashboard-2-ui-edgewise-meter#1]
![edge01](https://github.com/user-attachments/assets/c6b867a2-e1c3-4ee5-8d9d-a3f67bc2fd78)
Love this new widget, well done... I had to use it at once ;)

Is it possible to display the units like ° or % next to the main digit ?

just beeing curious ;) .. will this widget be available for vertical mode as well ?

**Comment by hotNipi** [comment]
The widget leans towards a real life device in terms of graphic design. Any extraneous information impairs readability. The unit of measurement does not change, repeating it even every other number is just noise.
Technically, it is of course possible to add a unit of measurement to numbers, but this creates several edge cases that are difficult to predict and the solution of which adds unreasonable complexity to the widget.
The label provides an opportunity to indicate the unit of measure if necessary.

The vertical layout should be drawn on paper before actually doing it. It contains several complex combinations, for example label can be a very long text, numbers can be multi-digit, etc.
If such a design is pre-planned and thought out, I have nothing against doing it.

**Comment by xX-Nexus-Xx** [comment]
I agree it can overload when put at every digit .. hmm... maybe you can put it just at the "Exact value" element

The vertical one was just a crazy idea, I understand the complexity for the layout ;) no rush on that .. lol

**Comment by hotNipi** [comment]
Unit to be displayed in exact value is reasonable.

**Comment by hotNipi** [comment]
Available since v 0.2.0
