### ISSUE TITLE
Errors after update to 0.4.1

### ISSUE THREAD

**Issue by TadyTheFish** [hotNipi/node-red-dashboard-2-ui-edgewise-meter#2]
I updated to 0.4.1 and Node red started throwing 
`"TypeError: Cannot read properties of undefined (reading 'indexOf')"`
Any ideas?
Thank you

**Comment by hotNipi** [comment]
It may happen and may take to remove the used instances and configure from scratch.

https://discourse.nodered.org/t/good-and-bad-news-about-my-gauges/93570

**Comment by TadyTheFish** [comment]
Oh man, i feel so stupid. Why didn't I try that!
Yes i needed to delete the gauges and reinsert them.

Thank you
